[project]
name = "apostador-ch-bot"
version = "0.1.0"
authors = [
    { name = "Caique Silva", email = "caique@email.com" }
]
description = "Bot para an√°lise adaptativa de jogos"
dependencies = [
    "pandas",
    "numpy",
    "scikit-learn",
    "matplotlib",
    "seaborn",
    "statsmodels"
]